// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Book struct {
	ID          int64  `json:"id"`
	Isbn        string `json:"isbn"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Author      string `json:"author"`
	ImageUrl    string `json:"image_url"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type UserBook struct {
	UserID     int64         `json:"user_id"`
	BookID     int64         `json:"book_id"`
	StartDate  sql.NullTime  `json:"start_date"`
	Progress   sql.NullInt64 `json:"progress"`
	FinishDate sql.NullTime  `json:"finish_date"`
	Rating     sql.NullInt64 `json:"rating"`
}
