/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SocialredirectImport } from './routes/socialredirect'
import { Route as RegisterImport } from './routes/register'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthDashboardImport } from './routes/_auth.dashboard'
import { Route as AuthBooksImport } from './routes/_auth.books'
import { Route as AuthDetailBookIdImport } from './routes/_auth.detail.$bookId'

// Create/Update Routes

const SocialredirectRoute = SocialredirectImport.update({
  id: '/socialredirect',
  path: '/socialredirect',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBooksRoute = AuthBooksImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDetailBookIdRoute = AuthDetailBookIdImport.update({
  id: '/detail/$bookId',
  path: '/detail/$bookId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/socialredirect': {
      id: '/socialredirect'
      path: '/socialredirect'
      fullPath: '/socialredirect'
      preLoaderRoute: typeof SocialredirectImport
      parentRoute: typeof rootRoute
    }
    '/_auth/books': {
      id: '/_auth/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthBooksImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/detail/$bookId': {
      id: '/_auth/detail/$bookId'
      path: '/detail/$bookId'
      fullPath: '/detail/$bookId'
      preLoaderRoute: typeof AuthDetailBookIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthBooksRoute: typeof AuthBooksRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDetailBookIdRoute: typeof AuthDetailBookIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBooksRoute: AuthBooksRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDetailBookIdRoute: AuthDetailBookIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/socialredirect': typeof SocialredirectRoute
  '/books': typeof AuthBooksRoute
  '/dashboard': typeof AuthDashboardRoute
  '/detail/$bookId': typeof AuthDetailBookIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/socialredirect': typeof SocialredirectRoute
  '/books': typeof AuthBooksRoute
  '/dashboard': typeof AuthDashboardRoute
  '/detail/$bookId': typeof AuthDetailBookIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/socialredirect': typeof SocialredirectRoute
  '/_auth/books': typeof AuthBooksRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/detail/$bookId': typeof AuthDetailBookIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/register'
    | '/socialredirect'
    | '/books'
    | '/dashboard'
    | '/detail/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/register'
    | '/socialredirect'
    | '/books'
    | '/dashboard'
    | '/detail/$bookId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/register'
    | '/socialredirect'
    | '/_auth/books'
    | '/_auth/dashboard'
    | '/_auth/detail/$bookId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SocialredirectRoute: typeof SocialredirectRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SocialredirectRoute: SocialredirectRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/register",
        "/socialredirect"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/books",
        "/_auth/dashboard",
        "/_auth/detail/$bookId"
      ]
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/socialredirect": {
      "filePath": "socialredirect.tsx"
    },
    "/_auth/books": {
      "filePath": "_auth.books.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard": {
      "filePath": "_auth.dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/detail/$bookId": {
      "filePath": "_auth.detail.$bookId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
